import { stripAiVendorMentions } from "@/lib/resume/stripAiVendorMentions";
import type {
  ResumeContact,
  ResumeContent,
  ResumeEducationEntry,
  ResumeProjectEntry,
  ResumeReferee,
} from "@/types";

/** The model's trimmed output: only the parts that require tailoring judgement. Contact
 * details, employers, job titles, dates, education, and referees are fixed facts supplied
 * separately (see FixedResumeFacts) and merged in below, never regenerated by the model. */
export interface TailoredResumeFields {
  target_titles: string[];
  summary: string;
  skills: string[];
  tools: string[];
  experience: { bullets: string[] }[];
  projects: ResumeProjectEntry[];
}

/** Facts a model call never sees or returns — taken straight from the profile (generate-resume)
 * or the existing resume row (retailor) and merged in structurally, so these fields can never be
 * altered or fabricated by the model since they never pass through it. */
export interface FixedResumeFacts {
  contact: ResumeContact;
  experience: {
    job_title: string;
    company: string;
    location: string;
    start_date: string;
    end_date: string;
  }[];
  education: ResumeEducationEntry[];
  referees: ResumeReferee[];
}

/**
 * Reconstructs the full ResumeContent the rest of the app expects (templates, preview, export,
 * factCheck) by merging a model's tailored output with fixed facts that never passed through the
 * model. Employers, job titles, dates, education, contact, and referees therefore can never be
 * altered or fabricated by generation or retailoring — they strengthen the never-fabricate
 * guarantee structurally rather than relying on prompt instructions alone.
 *
 * "experience" is matched by array position: both generate-resume and retailor's system prompts
 * instruct the model to return exactly one entry per role, in the same order as the fixed facts'
 * experience list.
 */
export function mergeResumeContent(tailored: TailoredResumeFields, fixed: FixedResumeFacts): ResumeContent {
  const tailoredExperience = tailored.experience ?? [];

  return {
    contact: fixed.contact,
    target_titles: tailored.target_titles ?? [],
    summary: tailored.summary ?? "",
    skills: stripAiVendorMentions(tailored.skills ?? []),
    tools: stripAiVendorMentions(tailored.tools ?? []),
    experience: fixed.experience.map((source, index) => ({
      job_title: source.job_title,
      company: source.company,
      company_description: "",
      location: source.location,
      start_date: source.start_date,
      end_date: source.end_date,
      bullets: tailoredExperience[index]?.bullets ?? [],
    })),
    projects: tailored.projects ?? [],
    education: fixed.education,
    referees: fixed.referees,
  };
}
