/** Australian universities, TAFEs and other large providers, suggested in education fields. */
export const INSTITUTION_CATALOG: readonly string[] = [
  "Australian National University", "University of Sydney", "University of Melbourne", "UNSW Sydney",
  "Monash University", "University of Queensland", "University of Western Australia", "University of Adelaide",
  "Adelaide University", "University of Technology Sydney", "Macquarie University", "RMIT University",
  "Deakin University", "Griffith University", "Queensland University of Technology", "Curtin University",
  "La Trobe University", "Western Sydney University", "University of Newcastle", "University of Wollongong",
  "Swinburne University of Technology", "Flinders University", "University of South Australia",
  "University of Tasmania", "James Cook University", "Murdoch University", "Edith Cowan University",
  "Australian Catholic University", "Charles Sturt University", "Victoria University", "Federation University",
  "Southern Cross University", "University of New England", "University of Canberra", "Charles Darwin University",
  "CQUniversity", "University of the Sunshine Coast", "University of Southern Queensland", "Bond University",
  "University of Notre Dame Australia", "Torrens University Australia", "Avondale University",
  "TAFE NSW", "TAFE Queensland", "TAFE SA", "North Metropolitan TAFE", "South Metropolitan TAFE",
  "Central Regional TAFE", "South Regional TAFE", "North Regional TAFE", "TasTAFE",
  "Canberra Institute of Technology", "Charles Darwin University VET", "Box Hill Institute",
  "Holmesglen Institute", "Melbourne Polytechnic", "Chisholm Institute", "William Angliss Institute",
  "Bendigo Kangan Institute", "Gordon TAFE", "South West TAFE", "Wodonga TAFE", "GOTAFE",
  "Open Universities Australia", "Kaplan Business School", "Le Cordon Bleu Australia",
  "Academy of Information Technology", "SAE University College", "JMC Academy",
  "Endeavour College of Natural Health", "Chartered Accountants ANZ", "CPA Australia",
  "Australian Institute of Company Directors", "General Assembly", "Coursera", "Udemy", "LinkedIn Learning",
];

/** Common Australian qualifications (AQF levels), suggested in degree/qualification fields. */
export const DEGREE_CATALOG: readonly string[] = [
  // Bachelor
  "Bachelor of Commerce", "Bachelor of Business", "Bachelor of Arts", "Bachelor of Science",
  "Bachelor of Engineering (Honours)", "Bachelor of Information Technology", "Bachelor of Computer Science",
  "Bachelor of Nursing", "Bachelor of Education (Primary)", "Bachelor of Education (Secondary)",
  "Bachelor of Early Childhood Education", "Bachelor of Laws", "Bachelor of Psychology",
  "Bachelor of Psychological Science", "Bachelor of Social Work", "Bachelor of Design",
  "Bachelor of Architecture", "Bachelor of Accounting", "Bachelor of Economics", "Bachelor of Finance",
  "Bachelor of Marketing", "Bachelor of Communication", "Bachelor of Media", "Bachelor of Health Science",
  "Bachelor of Exercise Science", "Bachelor of Physiotherapy", "Bachelor of Pharmacy",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)", "Bachelor of Midwifery", "Bachelor of Paramedicine",
  "Bachelor of Occupational Therapy", "Bachelor of Speech Pathology", "Bachelor of Biomedical Science",
  "Bachelor of Data Science", "Bachelor of Software Engineering", "Bachelor of Cyber Security",
  "Bachelor of Construction Management", "Bachelor of Property", "Bachelor of Hospitality Management",
  "Bachelor of Tourism", "Bachelor of Music", "Bachelor of Fine Arts", "Bachelor of Criminology",
  "Bachelor of International Studies", "Bachelor of Agriculture", "Bachelor of Environmental Science",
  "Bachelor of Veterinary Science", "Bachelor of Dental Surgery", "Honours degree", "Associate Degree",
  // Postgraduate
  "Master of Business Administration (MBA)", "Master of Commerce", "Master of Professional Accounting",
  "Master of Information Technology", "Master of Data Science", "Master of Business Analytics",
  "Master of Engineering", "Master of Education", "Master of Teaching", "Master of Nursing",
  "Master of Public Health", "Master of Social Work", "Master of Psychology", "Master of Laws (LLM)",
  "Juris Doctor (JD)", "Master of Project Management", "Master of Marketing", "Master of Finance",
  "Master of Architecture", "Master of Science", "Master of Arts", "Master of Cyber Security",
  "Doctor of Medicine (MD)", "Doctor of Philosophy (PhD)", "Graduate Certificate", "Graduate Diploma",
  "Graduate Diploma of Legal Practice", "Graduate Diploma of Education",
  // Vocational (VET)
  "Advanced Diploma", "Diploma of Nursing", "Diploma of Early Childhood Education and Care",
  "Diploma of Business", "Diploma of Leadership and Management", "Diploma of Project Management",
  "Diploma of Information Technology", "Diploma of Accounting", "Diploma of Marketing and Communication",
  "Diploma of Community Services", "Diploma of Hospitality Management", "Diploma of Graphic Design",
  "Diploma of Human Resource Management", "Diploma of Counselling", "Diploma of Beauty Therapy",
  "Diploma of Building and Construction",
  "Certificate IV in Training and Assessment", "Certificate IV in Ageing Support",
  "Certificate IV in Disability Support", "Certificate IV in Business Administration",
  "Certificate IV in Information Technology", "Certificate IV in Accounting and Bookkeeping",
  "Certificate IV in Mental Health", "Certificate IV in Fitness", "Certificate IV in Project Management Practice",
  "Certificate IV in Leadership and Management", "Certificate IV in Work Health and Safety",
  "Certificate IV in Building and Construction", "Certificate IV in Human Resource Management",
  "Certificate III in Individual Support", "Certificate III in Early Childhood Education and Care",
  "Certificate III in Business", "Certificate III in Hospitality", "Certificate III in Commercial Cookery",
  "Certificate III in Retail", "Certificate III in Fitness", "Certificate III in Electrotechnology Electrician",
  "Certificate III in Carpentry", "Certificate III in Plumbing",
  "Certificate III in Light Vehicle Mechanical Technology",
  "Certificate III in Heavy Commercial Vehicle Mechanical Technology",
  "Certificate III in Engineering - Fabrication Trade", "Certificate III in Hairdressing",
  "Certificate III in Beauty Services", "Certificate III in Warehousing Operations",
  "Certificate III in Security Operations", "Certificate III in Education Support",
  "Certificate III in Health Services Assistance", "Certificate III in Civil Construction",
  "Certificate III in Landscape Construction", "Certificate III in Baking",
  "Certificate II in Hospitality", "Certificate II in Retail Services", "Certificate II in Security Operations",
  "Certificate II in Kitchen Operations",
  // School
  "Higher School Certificate (HSC)", "Victorian Certificate of Education (VCE)",
  "Queensland Certificate of Education (QCE)", "Western Australian Certificate of Education (WACE)",
  "South Australian Certificate of Education (SACE)", "ACT Senior Secondary Certificate",
  "Tasmanian Certificate of Education (TCE)", "NT Certificate of Education and Training (NTCET)",
  "International Baccalaureate (IB)", "Year 12",
];
