// Location suggestions for the job profile. Names match Adzuna's location.area values (city and
// full state names), which is what the matching SQL compares against.
export const AU_LOCATIONS = [
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Canberra",
  "Hobart",
  "Darwin",
  "Gold Coast",
  "Newcastle",
  "Sunshine Coast",
  "Wollongong",
  "Geelong",
  "Townsville",
  "Cairns",
  "Toowoomba",
  "Ballarat",
  "Bendigo",
  "Launceston",
  "New South Wales",
  "Victoria",
  "Queensland",
  "Western Australia",
  "South Australia",
  "Tasmania",
  "Australian Capital Territory",
  "Northern Territory",
] as const;

/** Each city's state, so a suburb suggestion that repeats a city ("Sydney, NSW") can be dropped
 * without also hiding a same-named town elsewhere ("Perth, TAS"). */
export const CITY_STATES: Readonly<Record<string, string>> = {
  Sydney: "NSW",
  Melbourne: "VIC",
  Brisbane: "QLD",
  Perth: "WA",
  Adelaide: "SA",
  Canberra: "ACT",
  Hobart: "TAS",
  Darwin: "NT",
  "Gold Coast": "QLD",
  Newcastle: "NSW",
  "Sunshine Coast": "QLD",
  Wollongong: "NSW",
  Geelong: "VIC",
  Townsville: "QLD",
  Cairns: "QLD",
  Toowoomba: "QLD",
  Ballarat: "VIC",
  Bendigo: "VIC",
  Launceston: "TAS",
};
