// Location suggestions for the job profile. Names match Adzuna's location.area values (city and
// full state names), which is what the matching SQL compares against.
export const AU_LOCATIONS = [
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Canberra",
  "Hobart",
  "Darwin",
  "Gold Coast",
  "Newcastle",
  "Sunshine Coast",
  "Wollongong",
  "Geelong",
  "Townsville",
  "Cairns",
  "Toowoomba",
  "Ballarat",
  "Bendigo",
  "Launceston",
  "New South Wales",
  "Victoria",
  "Queensland",
  "Western Australia",
  "South Australia",
  "Tasmania",
  "Australian Capital Territory",
  "Northern Territory",
] as const;
